spack:
  concretizer:
    unify: when_possible

  view: false

  # O ambiente sempre será complementado por:
  # - site/: informações específicas da máquina
  # - common/: políticas e defaults compartilhados
  include:
  - site
  - common

  # Lista genérica dos pacotes necessários ao ambiente MPAS-JEDI.
  # Não fixa compilador nem versão específica de MPI da máquina.
  definitions:
  - packages:
    - python
    - esmf
    - ecmwf-atlas
    - ecbuild
    - eckit
    - fckit
    - parallelio
    - netcdf-c
    - netcdf-cxx4
    - netcdf-fortran
    - parallel-netcdf
    - gptl
    - jedi-cmake
    - gsl-lite
    - udunits
    - nccmp
    - py-pycodestyle

  # Expande a lista acima em specs concretos.
  specs:
  - $packages
