# cleaned site-oriented environment for MPAS-BUNDLE builds on EGEON
spack:
  concretizer:
    unify: when_possible
  view: false
  include:
  - site
  - common
  definitions:
  - compilers: ['%gcc@9.4.0']
  - packages:
    - openmpi
    - python
    - esmf
    - ecmwf-atlas
    - ecbuild
    - eckit
    - fckit
    - parallelio
    - netcdf-c
    - netcdf-cxx4
    - netcdf-fortran
    - parallel-netcdf
    - gptl
    - jedi-cmake
    - gsl-lite
    - udunits
    - nccmp
    - py-pycodestyle
  specs:
  - matrix:
    - [$packages]
    - [$compilers]
