packages:
  all:
    compiler:
    - gcc@9.4.0
    providers:
      mpi:
      - openmpi@4.1.1
    target:
    - core2

  mpi:
    buildable: false

  openmpi:
    buildable: false
    externals:
    - spec: openmpi@4.1.1%gcc@9.4.0
      modules:
      - gnu9/9.4.0
      - hwloc/2.5.0
      - ucx/1.11.2
      - libfabric/1.13.0
      - openmpi4/4.1.1
