# spack-stack style template (compatível com 1.7.0)
spack:
  concretizer:
    unify: when_possible
  view: false
  include:
  - site
  - common

  definitions:
  - compilers: ['%gcc@9.4.0']
  - packages:
    # Bases I/O/codificação
    - zlib
    - libpng
    - jpeg
    - jasper
    - hdf5+fortran+hl
    - netcdf-c
    - netcdf-fortran
    - eccodes
    # Coleção NCEP
    - bacio
    - w3emc
    - w3nco
    - sp
    - ip
    - g2c
    - sigio
    - sfcio
    - gfsio
    - nemsio
    - bufr
    # Obs/rad utilitários
    - crtm
    - wgrib2
    - nccmp

  specs:
  - matrix:
    - [$packages]
    - [$compilers]

